// <auto-generated />
using System;
using MAD.DataWarehouse.Payapps.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MAD.DataWarehouse.Payapps.Migrations
{
    [DbContext(typeof(PayappsDbContext))]
    [Migration("20220630014342_AddTable_PayappsListItemDto")]
    partial class AddTable_PayappsListItemDto
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Payapps.Api.PayappsListItemDto", b =>
                {
                    b.Property<double>("Claim_id")
                        .HasColumnType("float");

                    b.Property<string>("AdditionalProperties")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Approval_due_date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Approved_at")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Assessed")
                        .HasColumnType("float");

                    b.Property<string>("Claim_as_at")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Claim_seq_no")
                        .HasColumnType("float");

                    b.Property<string>("Claim_status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Claimant_invoice_ref")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Claimed")
                        .HasColumnType("float");

                    b.Property<double?>("Contra_approved")
                        .HasColumnType("float");

                    b.Property<double?>("Contra_this_approve")
                        .HasColumnType("float");

                    b.Property<double?>("Contract_id")
                        .HasColumnType("float");

                    b.Property<string>("Contract_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contract_ref")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Counterparty_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Counterparty_role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Discount_calc")
                        .HasColumnType("float");

                    b.Property<double?>("Discount_calc_at_approved")
                        .HasColumnType("float");

                    b.Property<double?>("Discount_this_claim")
                        .HasColumnType("float");

                    b.Property<double?>("Discounted_total_this_claim")
                        .HasColumnType("float");

                    b.Property<string>("External_integration_key_primary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Final_payment_due_date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Gross_approved")
                        .HasColumnType("float");

                    b.Property<double?>("Labour_approved_to_date")
                        .HasColumnType("float");

                    b.Property<double?>("Labour_claimed_to_date")
                        .HasColumnType("float");

                    b.Property<double?>("Lines_approved")
                        .HasColumnType("float");

                    b.Property<double?>("Lines_claimed")
                        .HasColumnType("float");

                    b.Property<double?>("Lines_this_approve")
                        .HasColumnType("float");

                    b.Property<double?>("Lines_this_claim")
                        .HasColumnType("float");

                    b.Property<double?>("Materials_approved")
                        .HasColumnType("float");

                    b.Property<double?>("Materials_claimed")
                        .HasColumnType("float");

                    b.Property<double?>("Materials_this_approve")
                        .HasColumnType("float");

                    b.Property<double?>("Materials_this_claim")
                        .HasColumnType("float");

                    b.Property<double?>("Mc_total_projected_amount")
                        .HasColumnType("float");

                    b.Property<double?>("Net_approved_before_taxes")
                        .HasColumnType("float");

                    b.Property<double?>("Net_approved_to_date")
                        .HasColumnType("float");

                    b.Property<double?>("Non_labour_to_date")
                        .HasColumnType("float");

                    b.Property<string>("Payment_due_date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Pln_is_draft")
                        .HasColumnType("bit");

                    b.Property<double?>("Pln_variance_this_claim")
                        .HasColumnType("float");

                    b.Property<string>("Pp_status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Previous_discount")
                        .HasColumnType("float");

                    b.Property<double?>("Previous_gross_approved")
                        .HasColumnType("float");

                    b.Property<double?>("Previous_net_approved_to_date")
                        .HasColumnType("float");

                    b.Property<double?>("Previous_retention")
                        .HasColumnType("float");

                    b.Property<string>("Project_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Project_ref")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Retention_approved_this_claim")
                        .HasColumnType("float");

                    b.Property<double?>("Retention_claimed_this_claim")
                        .HasColumnType("float");

                    b.Property<double?>("Retention_to_date")
                        .HasColumnType("float");

                    b.Property<double?>("Sc_total_projected_amount")
                        .HasColumnType("float");

                    b.Property<string>("Submitted_at")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Tax_this_claim_approved")
                        .HasColumnType("float");

                    b.Property<double?>("Tax_this_claim_submitted")
                        .HasColumnType("float");

                    b.Property<double?>("Varations_this_approve")
                        .HasColumnType("float");

                    b.Property<double?>("Variations_this_claim")
                        .HasColumnType("float");

                    b.Property<bool?>("Vat_reverse_charge_ind")
                        .HasColumnType("bit");

                    b.HasKey("Claim_id");

                    b.ToTable("PayappsListItemDto");
                });

            modelBuilder.Entity("Payapps.Api.ProjectDto", b =>
                {
                    b.Property<double>("Id")
                        .HasColumnType("float");

                    b.Property<string>("AdditionalProperties")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Authority_limits_enabled_ind")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("Commencement_date")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("Completion_date")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("Deleted_at")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("Enforce_approval_seq_ind")
                        .HasColumnType("bit");

                    b.Property<string>("External_integration_key_primary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("External_integration_key_secondary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Multiapproval_ind")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Project_ref")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Tax_rate")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("ProjectDto");
                });

            modelBuilder.Entity("Payapps.Api.ProjectDto", b =>
                {
                    b.OwnsOne("Payapps.Api.ProjectAddressDto", "Address", b1 =>
                        {
                            b1.Property<double>("ProjectDtoId")
                                .HasColumnType("float");

                            b1.Property<string>("AdditionalProperties")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Address_line_1")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Address_line_2")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Country")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Postcode")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Province")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("ProjectDtoId");

                            b1.ToTable("ProjectDto");

                            b1.WithOwner()
                                .HasForeignKey("ProjectDtoId");
                        });

                    b.OwnsOne("Payapps.Api.ProjectClaimCycleDto", "Claim_cycle", b1 =>
                        {
                            b1.Property<double>("ProjectDtoId")
                                .HasColumnType("float");

                            b1.Property<string>("AdditionalProperties")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<double>("Claim_due_day_of_month")
                                .HasColumnType("float");

                            b1.Property<string>("Fortnightly_start_date")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<double>("Period_end_day_of_month")
                                .HasColumnType("float");

                            b1.Property<double?>("Period_end_from_due_date")
                                .HasColumnType("float");

                            b1.Property<double>("Reminder_day_of_month")
                                .HasColumnType("float");

                            b1.Property<double?>("Reminder_days_pre_due_date")
                                .HasColumnType("float");

                            b1.Property<string>("Reminder_schedule")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("ProjectDtoId");

                            b1.ToTable("ProjectDto");

                            b1.WithOwner()
                                .HasForeignKey("ProjectDtoId");

                            b1.OwnsMany("Payapps.Api.ProjectClaimScheduleDto", "Claim_schedules", b2 =>
                                {
                                    b2.Property<double>("ProjectDtoId")
                                        .HasColumnType("float");

                                    b2.Property<double>("Id")
                                        .HasColumnType("float");

                                    b2.Property<string>("AdditionalProperties")
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("Due_date")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("End_date")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("Reminder_date")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("ProjectDtoId", "Id");

                                    b2.ToTable("ProjectClaimScheduleDto");

                                    b2.WithOwner()
                                        .HasForeignKey("ProjectDtoId");
                                });

                            b1.Navigation("Claim_schedules");
                        });

                    b.OwnsOne("Payapps.Api.ProjectPermissionsDto", "Permissions", b1 =>
                        {
                            b1.Property<double>("ProjectDtoId")
                                .HasColumnType("float");

                            b1.Property<string>("AdditionalProperties")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("ProjectDtoId");

                            b1.ToTable("ProjectDto");

                            b1.WithOwner()
                                .HasForeignKey("ProjectDtoId");

                            b1.OwnsMany("Payapps.Api.ProjectCategoryDto", "Project_categories", b2 =>
                                {
                                    b2.Property<double>("ProjectDtoId")
                                        .HasColumnType("float");

                                    b2.Property<double?>("Id")
                                        .HasColumnType("float");

                                    b2.Property<string>("AdditionalProperties")
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("Contract_count")
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("Project_category_name")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("ProjectDtoId", "Id");

                                    b2.ToTable("ProjectCategoryDto");

                                    b2.WithOwner()
                                        .HasForeignKey("ProjectDtoId");

                                    b2.OwnsMany("Payapps.Api.ProjectUsersDto", "Users", b3 =>
                                        {
                                            b3.Property<double>("ProjectDtoId")
                                                .HasColumnType("float");

                                            b3.Property<double>("ProjectCategoryDtoId")
                                                .HasColumnType("float");

                                            b3.Property<double>("Id")
                                                .HasColumnType("float");

                                            b3.Property<string>("AdditionalProperties")
                                                .HasColumnType("nvarchar(max)");

                                            b3.Property<string>("First_name")
                                                .HasColumnType("nvarchar(max)");

                                            b3.Property<string>("Last_name")
                                                .HasColumnType("nvarchar(max)");

                                            b3.Property<string>("Permissions")
                                                .IsRequired()
                                                .HasColumnType("nvarchar(max)");

                                            b3.Property<double>("Sequence")
                                                .HasColumnType("float");

                                            b3.HasKey("ProjectDtoId", "ProjectCategoryDtoId", "Id");

                                            b3.ToTable("ProjectUsersDto");

                                            b3.WithOwner()
                                                .HasForeignKey("ProjectDtoId", "ProjectCategoryDtoId");
                                        });

                                    b2.Navigation("Users");
                                });

                            b1.Navigation("Project_categories");
                        });

                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("Claim_cycle")
                        .IsRequired();

                    b.Navigation("Permissions")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
