// <auto-generated />
using System;
using MAD.DataWarehouse.Payapps.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MAD.DataWarehouse.Payapps.Migrations
{
    [DbContext(typeof(PayappsDbContext))]
    [Migration("20220630032405_AddTable_PayappsDto")]
    partial class AddTable_PayappsDto
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Payapps.Api.PayappDto", b =>
                {
                    b.Property<double>("Id")
                        .HasColumnType("float");

                    b.Property<bool?>("Acknowledge_instructions")
                        .HasColumnType("bit");

                    b.Property<string>("AdditionalProperties")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Approval_due_date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Approved_at")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Claim_as_at")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Claim_as_at_start")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Claim_limit_reached")
                        .HasColumnType("bit");

                    b.Property<string>("Claim_ref")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Claim_seq_no")
                        .HasColumnType("float");

                    b.Property<string>("Claim_status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Claimant_invoice_ref")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Contract_id")
                        .HasColumnType("float");

                    b.Property<string>("Contraitems")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Created_at")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Days_to_approve")
                        .HasColumnType("float");

                    b.Property<double?>("Labour_approved_this_claim")
                        .HasColumnType("float");

                    b.Property<double?>("Labour_approved_to_date")
                        .HasColumnType("float");

                    b.Property<double?>("Labour_claimed_this_claim")
                        .HasColumnType("float");

                    b.Property<double?>("Labour_claimed_to_date")
                        .HasColumnType("float");

                    b.Property<string>("Labour_mod_reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Labour_previous_approved")
                        .HasColumnType("float");

                    b.Property<string>("My_role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Organisation_id")
                        .HasColumnType("float");

                    b.Property<double?>("Pay_per_claim_credits")
                        .HasColumnType("float");

                    b.Property<double?>("Retention_applied")
                        .HasColumnType("float");

                    b.Property<double?>("Retention_calc")
                        .HasColumnType("float");

                    b.Property<double?>("Retention_calc_at_approved")
                        .HasColumnType("float");

                    b.Property<double?>("Retention_excl_release_this_claim")
                        .HasColumnType("float");

                    b.Property<bool?>("Retention_release_ind")
                        .HasColumnType("bit");

                    b.Property<double?>("Retention_release_requested")
                        .HasColumnType("float");

                    b.Property<double?>("Retention_released")
                        .HasColumnType("float");

                    b.Property<string>("Retention_released_mod_reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Retention_this_claim")
                        .HasColumnType("float");

                    b.Property<string>("Retention_withheld_mod_reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Retention_withheld_override")
                        .HasColumnType("float");

                    b.Property<string>("Submitted_at")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Tax_rate")
                        .HasColumnType("float");

                    b.Property<double?>("Total_approved")
                        .HasColumnType("float");

                    b.Property<double?>("Total_approved_orig")
                        .HasColumnType("float");

                    b.Property<double?>("Total_approved_to_date")
                        .HasColumnType("float");

                    b.Property<double?>("Total_approved_var")
                        .HasColumnType("float");

                    b.Property<double?>("Total_claimed")
                        .HasColumnType("float");

                    b.Property<double?>("Total_claimed_orig")
                        .HasColumnType("float");

                    b.Property<double?>("Total_claimed_var")
                        .HasColumnType("float");

                    b.Property<double?>("Total_this_claim")
                        .HasColumnType("float");

                    b.Property<double?>("Total_works")
                        .HasColumnType("float");

                    b.Property<bool?>("Variation_negotiation_enabled")
                        .HasColumnType("bit");

                    b.Property<string>("Variationitems")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PayappDto");
                });

            modelBuilder.Entity("Payapps.Api.PayappsListItemDto", b =>
                {
                    b.Property<double>("Claim_id")
                        .HasColumnType("float");

                    b.Property<string>("AdditionalProperties")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Approval_due_date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Approved_at")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Assessed")
                        .HasColumnType("float");

                    b.Property<string>("Claim_as_at")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Claim_seq_no")
                        .HasColumnType("float");

                    b.Property<string>("Claim_status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Claimant_invoice_ref")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Claimed")
                        .HasColumnType("float");

                    b.Property<double?>("Contra_approved")
                        .HasColumnType("float");

                    b.Property<double?>("Contra_this_approve")
                        .HasColumnType("float");

                    b.Property<double?>("Contract_id")
                        .HasColumnType("float");

                    b.Property<string>("Contract_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contract_ref")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Counterparty_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Counterparty_role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Discount_calc")
                        .HasColumnType("float");

                    b.Property<double?>("Discount_calc_at_approved")
                        .HasColumnType("float");

                    b.Property<double?>("Discount_this_claim")
                        .HasColumnType("float");

                    b.Property<double?>("Discounted_total_this_claim")
                        .HasColumnType("float");

                    b.Property<string>("External_integration_key_primary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Final_payment_due_date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Gross_approved")
                        .HasColumnType("float");

                    b.Property<double?>("Labour_approved_to_date")
                        .HasColumnType("float");

                    b.Property<double?>("Labour_claimed_to_date")
                        .HasColumnType("float");

                    b.Property<double?>("Lines_approved")
                        .HasColumnType("float");

                    b.Property<double?>("Lines_claimed")
                        .HasColumnType("float");

                    b.Property<double?>("Lines_this_approve")
                        .HasColumnType("float");

                    b.Property<double?>("Lines_this_claim")
                        .HasColumnType("float");

                    b.Property<double?>("Materials_approved")
                        .HasColumnType("float");

                    b.Property<double?>("Materials_claimed")
                        .HasColumnType("float");

                    b.Property<double?>("Materials_this_approve")
                        .HasColumnType("float");

                    b.Property<double?>("Materials_this_claim")
                        .HasColumnType("float");

                    b.Property<double?>("Mc_total_projected_amount")
                        .HasColumnType("float");

                    b.Property<double?>("Net_approved_before_taxes")
                        .HasColumnType("float");

                    b.Property<double?>("Net_approved_to_date")
                        .HasColumnType("float");

                    b.Property<double?>("Non_labour_to_date")
                        .HasColumnType("float");

                    b.Property<string>("Payment_due_date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Pln_is_draft")
                        .HasColumnType("bit");

                    b.Property<double?>("Pln_variance_this_claim")
                        .HasColumnType("float");

                    b.Property<string>("Pp_status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Previous_discount")
                        .HasColumnType("float");

                    b.Property<double?>("Previous_gross_approved")
                        .HasColumnType("float");

                    b.Property<double?>("Previous_net_approved_to_date")
                        .HasColumnType("float");

                    b.Property<double?>("Previous_retention")
                        .HasColumnType("float");

                    b.Property<string>("Project_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Project_ref")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Retention_approved_this_claim")
                        .HasColumnType("float");

                    b.Property<double?>("Retention_claimed_this_claim")
                        .HasColumnType("float");

                    b.Property<double?>("Retention_to_date")
                        .HasColumnType("float");

                    b.Property<double?>("Sc_total_projected_amount")
                        .HasColumnType("float");

                    b.Property<string>("Submitted_at")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Tax_this_claim_approved")
                        .HasColumnType("float");

                    b.Property<double?>("Tax_this_claim_submitted")
                        .HasColumnType("float");

                    b.Property<double?>("Varations_this_approve")
                        .HasColumnType("float");

                    b.Property<double?>("Variations_this_claim")
                        .HasColumnType("float");

                    b.Property<bool?>("Vat_reverse_charge_ind")
                        .HasColumnType("bit");

                    b.HasKey("Claim_id");

                    b.ToTable("PayappsListItemDto");
                });

            modelBuilder.Entity("Payapps.Api.ProjectDto", b =>
                {
                    b.Property<double>("Id")
                        .HasColumnType("float");

                    b.Property<string>("AdditionalProperties")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Authority_limits_enabled_ind")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("Commencement_date")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("Completion_date")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("Deleted_at")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("Enforce_approval_seq_ind")
                        .HasColumnType("bit");

                    b.Property<string>("External_integration_key_primary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("External_integration_key_secondary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Multiapproval_ind")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Project_ref")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Tax_rate")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("ProjectDto");
                });

            modelBuilder.Entity("Payapps.Api.PayappDto", b =>
                {
                    b.OwnsMany("Payapps.Api.ClaimlineSectionDto", "Lineitems", b1 =>
                        {
                            b1.Property<double>("PayappDtoId")
                                .HasColumnType("float");

                            b1.Property<string>("Id")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("AdditionalProperties")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("PayappDtoId", "Id");

                            b1.ToTable("ClaimlineSectionDto");

                            b1.WithOwner()
                                .HasForeignKey("PayappDtoId");

                            b1.OwnsMany("Payapps.Api.Nodes3", "Nodes", b2 =>
                                {
                                    b2.Property<double>("PayappDtoId")
                                        .HasColumnType("float");

                                    b2.Property<string>("ClaimlineSectionDtoId")
                                        .HasColumnType("nvarchar(450)");

                                    b2.Property<string>("Id")
                                        .HasColumnType("nvarchar(450)");

                                    b2.Property<string>("AdditionalProperties")
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("Description")
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("Line_ref_code")
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("Type")
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("PayappDtoId", "ClaimlineSectionDtoId", "Id");

                                    b2.ToTable("ClaimlineSectionDtoNode", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("PayappDtoId", "ClaimlineSectionDtoId");

                                    b2.OwnsOne("Payapps.Api.Claimline", "Claimline", b3 =>
                                        {
                                            b3.Property<double>("Nodes3PayappDtoId")
                                                .HasColumnType("float");

                                            b3.Property<string>("Nodes3ClaimlineSectionDtoId")
                                                .HasColumnType("nvarchar(450)");

                                            b3.Property<string>("Nodes3Id")
                                                .HasColumnType("nvarchar(450)");

                                            b3.Property<string>("ApprovalStatus")
                                                .HasColumnType("nvarchar(max)");

                                            b3.Property<long?>("ApproveAmt")
                                                .HasColumnType("bigint");

                                            b3.Property<double?>("ApprovePct")
                                                .HasColumnType("float");

                                            b3.Property<long?>("ApproveQty")
                                                .HasColumnType("bigint");

                                            b3.Property<long?>("ApproveValAtEnd")
                                                .HasColumnType("bigint");

                                            b3.Property<long?>("ApprovedToDate")
                                                .HasColumnType("bigint");

                                            b3.Property<long?>("ApprovedToDateQty")
                                                .HasColumnType("bigint");

                                            b3.Property<long?>("ClaimAmt")
                                                .HasColumnType("bigint");

                                            b3.Property<long?>("ClaimId")
                                                .HasColumnType("bigint");

                                            b3.Property<long?>("ClaimLineId")
                                                .HasColumnType("bigint");

                                            b3.Property<double?>("ClaimPct")
                                                .HasColumnType("float");

                                            b3.Property<long?>("ClaimQty")
                                                .HasColumnType("bigint");

                                            b3.Property<string>("ClaimStatus")
                                                .HasColumnType("nvarchar(max)");

                                            b3.Property<long?>("ClaimValAtEnd")
                                                .HasColumnType("bigint");

                                            b3.Property<long?>("ClaimantProjectedQty")
                                                .HasColumnType("bigint");

                                            b3.Property<long?>("ClaimantProjectedRate")
                                                .HasColumnType("bigint");

                                            b3.Property<long?>("ContractId")
                                                .HasColumnType("bigint");

                                            b3.Property<DateTimeOffset?>("ContractLineCreatedAt")
                                                .HasColumnType("datetimeoffset");

                                            b3.Property<long?>("ContractLineId")
                                                .HasColumnType("bigint");

                                            b3.Property<string>("ContractLineType")
                                                .HasColumnType("nvarchar(max)");

                                            b3.Property<DateTimeOffset?>("CreatedAt")
                                                .HasColumnType("datetimeoffset");

                                            b3.Property<string>("Description")
                                                .HasColumnType("nvarchar(max)");

                                            b3.Property<bool?>("DiscountInd")
                                                .HasColumnType("bit");

                                            b3.Property<string>("ExternalIntegrationKeyPrimary")
                                                .HasColumnType("nvarchar(max)");

                                            b3.Property<string>("Heading")
                                                .HasColumnType("nvarchar(max)");

                                            b3.Property<bool?>("HistoricalInd")
                                                .HasColumnType("bit");

                                            b3.Property<long?>("Id")
                                                .HasColumnType("bigint");

                                            b3.Property<string>("LineRefCode")
                                                .HasColumnType("nvarchar(max)");

                                            b3.Property<bool?>("LockedAmount")
                                                .HasColumnType("bit");

                                            b3.Property<bool?>("LockedInd")
                                                .HasColumnType("bit");

                                            b3.Property<bool?>("LumpSumInd")
                                                .HasColumnType("bit");

                                            b3.Property<long?>("NewActivityCount")
                                                .HasColumnType("bigint");

                                            b3.Property<long?>("Qty")
                                                .HasColumnType("bigint");

                                            b3.Property<long?>("QtyAtApproved")
                                                .HasColumnType("bigint");

                                            b3.Property<long?>("QtyAtClaimed")
                                                .HasColumnType("bigint");

                                            b3.Property<long?>("Rate")
                                                .HasColumnType("bigint");

                                            b3.Property<long?>("RateAtApproved")
                                                .HasColumnType("bigint");

                                            b3.Property<long?>("RateAtClaimed")
                                                .HasColumnType("bigint");

                                            b3.Property<bool?>("RetExclInd")
                                                .HasColumnType("bit");

                                            b3.Property<string>("StatusAtApproved")
                                                .HasColumnType("nvarchar(max)");

                                            b3.Property<string>("StatusAtClaimed")
                                                .HasColumnType("nvarchar(max)");

                                            b3.Property<bool?>("TaxExemptInd")
                                                .HasColumnType("bit");

                                            b3.Property<long?>("TaxRate")
                                                .HasColumnType("bigint");

                                            b3.Property<long?>("ThisApproveAmt")
                                                .HasColumnType("bigint");

                                            b3.Property<double?>("ThisApprovePct")
                                                .HasColumnType("float");

                                            b3.Property<long?>("ThisApproveQty")
                                                .HasColumnType("bigint");

                                            b3.Property<long?>("ThisClaimAmt")
                                                .HasColumnType("bigint");

                                            b3.Property<double?>("ThisClaimPct")
                                                .HasColumnType("float");

                                            b3.Property<long?>("ThisClaimQty")
                                                .HasColumnType("bigint");

                                            b3.Property<long?>("TotalActivityCount")
                                                .HasColumnType("bigint");

                                            b3.Property<Guid?>("Uid")
                                                .HasColumnType("uniqueidentifier");

                                            b3.Property<string>("UnitType")
                                                .HasColumnType("nvarchar(max)");

                                            b3.Property<bool?>("VariableBudgetInd")
                                                .HasColumnType("bit");

                                            b3.Property<long?>("WhenComplete")
                                                .HasColumnType("bigint");

                                            b3.HasKey("Nodes3PayappDtoId", "Nodes3ClaimlineSectionDtoId", "Nodes3Id");

                                            b3.ToTable("ClaimlineSectionDtoNode");

                                            b3.WithOwner()
                                                .HasForeignKey("Nodes3PayappDtoId", "Nodes3ClaimlineSectionDtoId", "Nodes3Id");
                                        });

                                    b2.OwnsMany("Payapps.Api.ClaimlinesLineDto", "Nodes", b3 =>
                                        {
                                            b3.Property<double>("PayappDtoId")
                                                .HasColumnType("float");

                                            b3.Property<string>("ClaimlineSectionDtoId")
                                                .HasColumnType("nvarchar(450)");

                                            b3.Property<string>("ClaimlineSectionDtoNodeId")
                                                .HasColumnType("nvarchar(450)");

                                            b3.Property<string>("Id")
                                                .HasColumnType("nvarchar(450)");

                                            b3.Property<string>("AdditionalProperties")
                                                .HasColumnType("nvarchar(max)");

                                            b3.Property<string>("Type")
                                                .IsRequired()
                                                .HasColumnType("nvarchar(max)");

                                            b3.HasKey("PayappDtoId", "ClaimlineSectionDtoId", "ClaimlineSectionDtoNodeId", "Id");

                                            b3.ToTable("ClaimlinesLineDto");

                                            b3.WithOwner()
                                                .HasForeignKey("PayappDtoId", "ClaimlineSectionDtoId", "ClaimlineSectionDtoNodeId");

                                            b3.OwnsOne("Payapps.Api.Claimline", "Claimline", b4 =>
                                                {
                                                    b4.Property<double>("ClaimlinesLineDtoPayappDtoId")
                                                        .HasColumnType("float");

                                                    b4.Property<string>("ClaimlinesLineDtoClaimlineSectionDtoId")
                                                        .HasColumnType("nvarchar(450)");

                                                    b4.Property<string>("ClaimlinesLineDtoClaimlineSectionDtoNodeId")
                                                        .HasColumnType("nvarchar(450)");

                                                    b4.Property<string>("ClaimlinesLineDtoId")
                                                        .HasColumnType("nvarchar(450)");

                                                    b4.Property<string>("ApprovalStatus")
                                                        .HasColumnType("nvarchar(max)");

                                                    b4.Property<long?>("ApproveAmt")
                                                        .HasColumnType("bigint");

                                                    b4.Property<double?>("ApprovePct")
                                                        .HasColumnType("float");

                                                    b4.Property<long?>("ApproveQty")
                                                        .HasColumnType("bigint");

                                                    b4.Property<long?>("ApproveValAtEnd")
                                                        .HasColumnType("bigint");

                                                    b4.Property<long?>("ApprovedToDate")
                                                        .HasColumnType("bigint");

                                                    b4.Property<long?>("ApprovedToDateQty")
                                                        .HasColumnType("bigint");

                                                    b4.Property<long?>("ClaimAmt")
                                                        .HasColumnType("bigint");

                                                    b4.Property<long?>("ClaimId")
                                                        .HasColumnType("bigint");

                                                    b4.Property<long?>("ClaimLineId")
                                                        .HasColumnType("bigint");

                                                    b4.Property<double?>("ClaimPct")
                                                        .HasColumnType("float");

                                                    b4.Property<long?>("ClaimQty")
                                                        .HasColumnType("bigint");

                                                    b4.Property<string>("ClaimStatus")
                                                        .HasColumnType("nvarchar(max)");

                                                    b4.Property<long?>("ClaimValAtEnd")
                                                        .HasColumnType("bigint");

                                                    b4.Property<long?>("ClaimantProjectedQty")
                                                        .HasColumnType("bigint");

                                                    b4.Property<long?>("ClaimantProjectedRate")
                                                        .HasColumnType("bigint");

                                                    b4.Property<long?>("ContractId")
                                                        .HasColumnType("bigint");

                                                    b4.Property<DateTimeOffset?>("ContractLineCreatedAt")
                                                        .HasColumnType("datetimeoffset");

                                                    b4.Property<long?>("ContractLineId")
                                                        .HasColumnType("bigint");

                                                    b4.Property<string>("ContractLineType")
                                                        .HasColumnType("nvarchar(max)");

                                                    b4.Property<DateTimeOffset?>("CreatedAt")
                                                        .HasColumnType("datetimeoffset");

                                                    b4.Property<string>("Description")
                                                        .HasColumnType("nvarchar(max)");

                                                    b4.Property<bool?>("DiscountInd")
                                                        .HasColumnType("bit");

                                                    b4.Property<string>("ExternalIntegrationKeyPrimary")
                                                        .HasColumnType("nvarchar(max)");

                                                    b4.Property<string>("Heading")
                                                        .HasColumnType("nvarchar(max)");

                                                    b4.Property<bool?>("HistoricalInd")
                                                        .HasColumnType("bit");

                                                    b4.Property<long?>("Id")
                                                        .HasColumnType("bigint");

                                                    b4.Property<string>("LineRefCode")
                                                        .HasColumnType("nvarchar(max)");

                                                    b4.Property<bool?>("LockedAmount")
                                                        .HasColumnType("bit");

                                                    b4.Property<bool?>("LockedInd")
                                                        .HasColumnType("bit");

                                                    b4.Property<bool?>("LumpSumInd")
                                                        .HasColumnType("bit");

                                                    b4.Property<long?>("NewActivityCount")
                                                        .HasColumnType("bigint");

                                                    b4.Property<long?>("Qty")
                                                        .HasColumnType("bigint");

                                                    b4.Property<long?>("QtyAtApproved")
                                                        .HasColumnType("bigint");

                                                    b4.Property<long?>("QtyAtClaimed")
                                                        .HasColumnType("bigint");

                                                    b4.Property<long?>("Rate")
                                                        .HasColumnType("bigint");

                                                    b4.Property<long?>("RateAtApproved")
                                                        .HasColumnType("bigint");

                                                    b4.Property<long?>("RateAtClaimed")
                                                        .HasColumnType("bigint");

                                                    b4.Property<bool?>("RetExclInd")
                                                        .HasColumnType("bit");

                                                    b4.Property<string>("StatusAtApproved")
                                                        .HasColumnType("nvarchar(max)");

                                                    b4.Property<string>("StatusAtClaimed")
                                                        .HasColumnType("nvarchar(max)");

                                                    b4.Property<bool?>("TaxExemptInd")
                                                        .HasColumnType("bit");

                                                    b4.Property<long?>("TaxRate")
                                                        .HasColumnType("bigint");

                                                    b4.Property<long?>("ThisApproveAmt")
                                                        .HasColumnType("bigint");

                                                    b4.Property<double?>("ThisApprovePct")
                                                        .HasColumnType("float");

                                                    b4.Property<long?>("ThisApproveQty")
                                                        .HasColumnType("bigint");

                                                    b4.Property<long?>("ThisClaimAmt")
                                                        .HasColumnType("bigint");

                                                    b4.Property<double?>("ThisClaimPct")
                                                        .HasColumnType("float");

                                                    b4.Property<long?>("ThisClaimQty")
                                                        .HasColumnType("bigint");

                                                    b4.Property<long?>("TotalActivityCount")
                                                        .HasColumnType("bigint");

                                                    b4.Property<Guid?>("Uid")
                                                        .HasColumnType("uniqueidentifier");

                                                    b4.Property<string>("UnitType")
                                                        .HasColumnType("nvarchar(max)");

                                                    b4.Property<bool?>("VariableBudgetInd")
                                                        .HasColumnType("bit");

                                                    b4.Property<long?>("WhenComplete")
                                                        .HasColumnType("bigint");

                                                    b4.HasKey("ClaimlinesLineDtoPayappDtoId", "ClaimlinesLineDtoClaimlineSectionDtoId", "ClaimlinesLineDtoClaimlineSectionDtoNodeId", "ClaimlinesLineDtoId");

                                                    b4.ToTable("ClaimlinesLineDto");

                                                    b4.WithOwner()
                                                        .HasForeignKey("ClaimlinesLineDtoPayappDtoId", "ClaimlinesLineDtoClaimlineSectionDtoId", "ClaimlinesLineDtoClaimlineSectionDtoNodeId", "ClaimlinesLineDtoId");
                                                });

                                            b3.Navigation("Claimline")
                                                .IsRequired();
                                        });

                                    b2.Navigation("Claimline");

                                    b2.Navigation("Nodes");
                                });

                            b1.Navigation("Nodes");
                        });

                    b.OwnsMany("Payapps.Api.MateriallinesSectionDto", "Materialitems", b1 =>
                        {
                            b1.Property<double>("PayappDtoId")
                                .HasColumnType("float");

                            b1.Property<string>("Id")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("AdditionalProperties")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Line_ref_code")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("PayappDtoId", "Id");

                            b1.ToTable("MateriallinesSectionDto");

                            b1.WithOwner()
                                .HasForeignKey("PayappDtoId");

                            b1.OwnsMany("Payapps.Api.MateriallinesHeadingDto", "Nodes", b2 =>
                                {
                                    b2.Property<double>("PayappDtoId")
                                        .HasColumnType("float");

                                    b2.Property<string>("MateriallinesSectionDtoId")
                                        .HasColumnType("nvarchar(450)");

                                    b2.Property<string>("Id")
                                        .HasColumnType("nvarchar(450)");

                                    b2.Property<string>("AdditionalProperties")
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("Description")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("Line_ref_code")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("Type")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("PayappDtoId", "MateriallinesSectionDtoId", "Id");

                                    b2.ToTable("MateriallinesHeadingDto");

                                    b2.WithOwner()
                                        .HasForeignKey("PayappDtoId", "MateriallinesSectionDtoId");

                                    b2.OwnsMany("Payapps.Api.MateriallinesLineDto", "Nodes", b3 =>
                                        {
                                            b3.Property<double>("PayappDtoId")
                                                .HasColumnType("float");

                                            b3.Property<string>("MateriallinesSectionDtoId")
                                                .HasColumnType("nvarchar(450)");

                                            b3.Property<string>("MateriallinesHeadingDtoId")
                                                .HasColumnType("nvarchar(450)");

                                            b3.Property<double>("Id")
                                                .HasColumnType("float");

                                            b3.Property<string>("AdditionalProperties")
                                                .HasColumnType("nvarchar(max)");

                                            b3.Property<string>("Created_at")
                                                .IsRequired()
                                                .HasColumnType("nvarchar(max)");

                                            b3.Property<double>("Created_by_organisation")
                                                .HasColumnType("float");

                                            b3.Property<string>("Deleted_at")
                                                .IsRequired()
                                                .HasColumnType("nvarchar(max)");

                                            b3.Property<string>("Description")
                                                .IsRequired()
                                                .HasColumnType("nvarchar(max)");

                                            b3.Property<string>("Line_ref_code")
                                                .IsRequired()
                                                .HasColumnType("nvarchar(max)");

                                            b3.Property<double>("Modification_reason")
                                                .HasColumnType("float");

                                            b3.Property<double>("Modification_reason_comment")
                                                .HasColumnType("float");

                                            b3.Property<double>("New_activity_count")
                                                .HasColumnType("float");

                                            b3.Property<double>("Prev_approved")
                                                .HasColumnType("float");

                                            b3.Property<double>("Qty_at_approved")
                                                .HasColumnType("float");

                                            b3.Property<double>("Qty_at_claimed")
                                                .HasColumnType("float");

                                            b3.Property<double>("Rate_at_approved")
                                                .HasColumnType("float");

                                            b3.Property<double>("Rate_at_claimed")
                                                .HasColumnType("float");

                                            b3.Property<double>("Total_activity_count")
                                                .HasColumnType("float");

                                            b3.Property<string>("Type")
                                                .IsRequired()
                                                .HasColumnType("nvarchar(max)");

                                            b3.Property<string>("Unit_type")
                                                .IsRequired()
                                                .HasColumnType("nvarchar(max)");

                                            b3.HasKey("PayappDtoId", "MateriallinesSectionDtoId", "MateriallinesHeadingDtoId", "Id");

                                            b3.ToTable("MateriallinesLineDto");

                                            b3.WithOwner()
                                                .HasForeignKey("PayappDtoId", "MateriallinesSectionDtoId", "MateriallinesHeadingDtoId");
                                        });

                                    b2.Navigation("Nodes");
                                });

                            b1.Navigation("Nodes");
                        });

                    b.OwnsMany("Payapps.Api.PayappActionHistoryDto", "Action_history", b1 =>
                        {
                            b1.Property<double>("PayappDtoId")
                                .HasColumnType("float");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"), 1L, 1);

                            b1.Property<string>("Action")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("AdditionalProperties")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Created_at")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("First_name")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Last_name")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<double>("User_id")
                                .HasColumnType("float");

                            b1.HasKey("PayappDtoId", "Id");

                            b1.ToTable("PayappActionHistoryDto");

                            b1.WithOwner()
                                .HasForeignKey("PayappDtoId");
                        });

                    b.OwnsOne("Payapps.Api.PayappPlnDto", "Pln", b1 =>
                        {
                            b1.Property<double>("PayappDtoId")
                                .HasColumnType("float");

                            b1.Property<string>("AdditionalProperties")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Adjustments")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Approved_at")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Deleted_at")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<bool>("Eligible")
                                .HasColumnType("bit");

                            b1.Property<double>("Id")
                                .HasColumnType("float");

                            b1.HasKey("PayappDtoId");

                            b1.ToTable("PayappDto");

                            b1.WithOwner()
                                .HasForeignKey("PayappDtoId");
                        });

                    b.OwnsOne("Payapps.Api.PayappsSummaryDto", "Summary", b1 =>
                        {
                            b1.Property<double>("PayappDtoId")
                                .HasColumnType("float");

                            b1.Property<string>("AdditionalProperties")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("PayappDtoId");

                            b1.ToTable("PayappDto");

                            b1.WithOwner()
                                .HasForeignKey("PayappDtoId");

                            b1.OwnsOne("Payapps.Api.PayappsSummaryItemDto", "This_claim", b2 =>
                                {
                                    b2.Property<double>("PayappsSummaryDtoPayappDtoId")
                                        .HasColumnType("float");

                                    b2.Property<string>("AdditionalProperties")
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<double>("Cash_retention")
                                        .HasColumnType("float");

                                    b2.Property<double>("Cash_retention_tax")
                                        .HasColumnType("float");

                                    b2.Property<double>("Contra_charges")
                                        .HasColumnType("float");

                                    b2.Property<double>("Discount")
                                        .HasColumnType("float");

                                    b2.Property<double>("Discount_coefficient")
                                        .HasColumnType("float");

                                    b2.Property<double>("Discounted_total")
                                        .HasColumnType("float");

                                    b2.Property<double>("Financeable_tax")
                                        .HasColumnType("float");

                                    b2.Property<double>("Materials")
                                        .HasColumnType("float");

                                    b2.Property<double>("Net_claim_excl_tax")
                                        .HasColumnType("float");

                                    b2.Property<double>("Net_claim_incl_tax")
                                        .HasColumnType("float");

                                    b2.Property<double>("Original_works")
                                        .HasColumnType("float");

                                    b2.Property<double>("Retention_released")
                                        .HasColumnType("float");

                                    b2.Property<double>("Retention_withheld")
                                        .HasColumnType("float");

                                    b2.Property<double>("Revised_works")
                                        .HasColumnType("float");

                                    b2.Property<double>("Revised_works_and_voa")
                                        .HasColumnType("float");

                                    b2.Property<double>("Tax")
                                        .HasColumnType("float");

                                    b2.Property<double>("Variations_approved")
                                        .HasColumnType("float");

                                    b2.Property<double>("Variations_on_account")
                                        .HasColumnType("float");

                                    b2.Property<double>("Variations_rejected")
                                        .HasColumnType("float");

                                    b2.HasKey("PayappsSummaryDtoPayappDtoId");

                                    b2.ToTable("PayappDto");

                                    b2.WithOwner()
                                        .HasForeignKey("PayappsSummaryDtoPayappDtoId");
                                });

                            b1.Navigation("This_claim")
                                .IsRequired();
                        });

                    b.Navigation("Action_history");

                    b.Navigation("Lineitems");

                    b.Navigation("Materialitems");

                    b.Navigation("Pln");

                    b.Navigation("Summary");
                });

            modelBuilder.Entity("Payapps.Api.ProjectDto", b =>
                {
                    b.OwnsOne("Payapps.Api.ProjectAddressDto", "Address", b1 =>
                        {
                            b1.Property<double>("ProjectDtoId")
                                .HasColumnType("float");

                            b1.Property<string>("AdditionalProperties")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Address_line_1")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Address_line_2")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Country")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Postcode")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Province")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("ProjectDtoId");

                            b1.ToTable("ProjectDto");

                            b1.WithOwner()
                                .HasForeignKey("ProjectDtoId");
                        });

                    b.OwnsOne("Payapps.Api.ProjectClaimCycleDto", "Claim_cycle", b1 =>
                        {
                            b1.Property<double>("ProjectDtoId")
                                .HasColumnType("float");

                            b1.Property<string>("AdditionalProperties")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<double>("Claim_due_day_of_month")
                                .HasColumnType("float");

                            b1.Property<string>("Fortnightly_start_date")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<double>("Period_end_day_of_month")
                                .HasColumnType("float");

                            b1.Property<double?>("Period_end_from_due_date")
                                .HasColumnType("float");

                            b1.Property<double>("Reminder_day_of_month")
                                .HasColumnType("float");

                            b1.Property<double?>("Reminder_days_pre_due_date")
                                .HasColumnType("float");

                            b1.Property<string>("Reminder_schedule")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("ProjectDtoId");

                            b1.ToTable("ProjectDto");

                            b1.WithOwner()
                                .HasForeignKey("ProjectDtoId");

                            b1.OwnsMany("Payapps.Api.ProjectClaimScheduleDto", "Claim_schedules", b2 =>
                                {
                                    b2.Property<double>("ProjectDtoId")
                                        .HasColumnType("float");

                                    b2.Property<double>("Id")
                                        .HasColumnType("float");

                                    b2.Property<string>("AdditionalProperties")
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("Due_date")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("End_date")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("Reminder_date")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("ProjectDtoId", "Id");

                                    b2.ToTable("ProjectClaimScheduleDto");

                                    b2.WithOwner()
                                        .HasForeignKey("ProjectDtoId");
                                });

                            b1.Navigation("Claim_schedules");
                        });

                    b.OwnsOne("Payapps.Api.ProjectPermissionsDto", "Permissions", b1 =>
                        {
                            b1.Property<double>("ProjectDtoId")
                                .HasColumnType("float");

                            b1.Property<string>("AdditionalProperties")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("ProjectDtoId");

                            b1.ToTable("ProjectDto");

                            b1.WithOwner()
                                .HasForeignKey("ProjectDtoId");

                            b1.OwnsMany("Payapps.Api.ProjectCategoryDto", "Project_categories", b2 =>
                                {
                                    b2.Property<double>("ProjectDtoId")
                                        .HasColumnType("float");

                                    b2.Property<double?>("Id")
                                        .HasColumnType("float");

                                    b2.Property<string>("AdditionalProperties")
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("Contract_count")
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("Project_category_name")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("ProjectDtoId", "Id");

                                    b2.ToTable("ProjectCategoryDto");

                                    b2.WithOwner()
                                        .HasForeignKey("ProjectDtoId");

                                    b2.OwnsMany("Payapps.Api.ProjectUsersDto", "Users", b3 =>
                                        {
                                            b3.Property<double>("ProjectDtoId")
                                                .HasColumnType("float");

                                            b3.Property<double>("ProjectCategoryDtoId")
                                                .HasColumnType("float");

                                            b3.Property<double>("Id")
                                                .HasColumnType("float");

                                            b3.Property<string>("AdditionalProperties")
                                                .HasColumnType("nvarchar(max)");

                                            b3.Property<string>("First_name")
                                                .HasColumnType("nvarchar(max)");

                                            b3.Property<string>("Last_name")
                                                .HasColumnType("nvarchar(max)");

                                            b3.Property<string>("Permissions")
                                                .IsRequired()
                                                .HasColumnType("nvarchar(max)");

                                            b3.Property<double>("Sequence")
                                                .HasColumnType("float");

                                            b3.HasKey("ProjectDtoId", "ProjectCategoryDtoId", "Id");

                                            b3.ToTable("ProjectUsersDto");

                                            b3.WithOwner()
                                                .HasForeignKey("ProjectDtoId", "ProjectCategoryDtoId");
                                        });

                                    b2.Navigation("Users");
                                });

                            b1.Navigation("Project_categories");
                        });

                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("Claim_cycle")
                        .IsRequired();

                    b.Navigation("Permissions")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
